services:
  postgres1:
    image: postgres:15
    container_name: postgres-shard1
    environment:
      POSTGRES_DB: shard-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"

  postgres2:
    image: postgres:15
    container_name: postgres-shard2
    environment:
      POSTGRES_DB: shard-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"

  postgres3:
    image: postgres:15
    container_name: postgres-shard3
    environment:
      POSTGRES_DB: shard-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5435:5432"
