services:
  lazymc:
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    container_name: mc-proxy
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ${VOLUMES_DIR}/data:/server:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      minecraft:
        ipv4_address: 172.30.0.2

  minecraft:
    image: itzg/minecraft-server:java25
    container_name: mc-purpur
    restart: "no"
    expose:
      - "25565"
    networks:
      minecraft:
        ipv4_address: 172.30.0.3
    labels:
      - "lazymc.enabled=true"
      - "lazymc.group=minecraft"
      - "lazymc.server.address=minecraft:25565"
      - "lazymc.time.sleep_after=1200"
      - "lazymc.time.minimum_online_time=300"
      - "lazymc.join.hold.timeout=25"
      - "lazymc.motd.sleeping=§7Servidor dormindo - conecte para iniciar"
    tty: true
    stdin_open: true
    volumes:
      - ${VOLUMES_DIR}/data:/data
      - ${VOLUMES_DIR}/plugins:/plugins
    environment:
      - VERSION=26.2
      - TZ=UTC
      - EULA=TRUE
      - TYPE=PURPUR
      - MEMORY=2G
      - LEVEL=Poguelandia
      - ONLINE_MODE=FALSE
      - OPS=Brunoozzy,sucrilhos303,xlFox

networks:
  minecraft:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
