// Code generated by MockGen. DO NOT EDIT.
// Source: planning-poker/internal/application/lock (interfaces: LockManager)
//
// Generated by this command:
//
//	mockgen -destination mocks.go -typed -package lock . LockManager
//

// Package lock is a generated GoMock package.
package lock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLockManager is a mock of LockManager interface.
type MockLockManager struct {
	ctrl     *gomock.Controller
	recorder *MockLockManagerMockRecorder
	isgomock struct{}
}

// MockLockManagerMockRecorder is the mock recorder for MockLockManager.
type MockLockManagerMockRecorder struct {
	mock *MockLockManager
}

// NewMockLockManager creates a new mock instance.
func NewMockLockManager(ctrl *gomock.Controller) *MockLockManager {
	mock := &MockLockManager{ctrl: ctrl}
	mock.recorder = &MockLockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockManager) EXPECT() *MockLockManagerMockRecorder {
	return m.recorder
}

// ExecuteWithLock mocks base method.
func (m *MockLockManager) ExecuteWithLock(ctx context.Context, key string, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWithLock", ctx, key, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteWithLock indicates an expected call of ExecuteWithLock.
func (mr *MockLockManagerMockRecorder) ExecuteWithLock(ctx, key, fn any) *MockLockManagerExecuteWithLockCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWithLock", reflect.TypeOf((*MockLockManager)(nil).ExecuteWithLock), ctx, key, fn)
	return &MockLockManagerExecuteWithLockCall{Call: call}
}

// MockLockManagerExecuteWithLockCall wrap *gomock.Call
type MockLockManagerExecuteWithLockCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLockManagerExecuteWithLockCall) Return(arg0 error) *MockLockManagerExecuteWithLockCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLockManagerExecuteWithLockCall) Do(f func(context.Context, string, func(context.Context) error) error) *MockLockManagerExecuteWithLockCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLockManagerExecuteWithLockCall) DoAndReturn(f func(context.Context, string, func(context.Context) error) error) *MockLockManagerExecuteWithLockCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WithLock mocks base method.
func (m *MockLockManager) WithLock(ctx context.Context, key string, fn func(context.Context) (any, error)) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithLock", ctx, key, fn)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithLock indicates an expected call of WithLock.
func (mr *MockLockManagerMockRecorder) WithLock(ctx, key, fn any) *MockLockManagerWithLockCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithLock", reflect.TypeOf((*MockLockManager)(nil).WithLock), ctx, key, fn)
	return &MockLockManagerWithLockCall{Call: call}
}

// MockLockManagerWithLockCall wrap *gomock.Call
type MockLockManagerWithLockCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLockManagerWithLockCall) Return(arg0 any, arg1 error) *MockLockManagerWithLockCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLockManagerWithLockCall) Do(f func(context.Context, string, func(context.Context) (any, error)) (any, error)) *MockLockManagerWithLockCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLockManagerWithLockCall) DoAndReturn(f func(context.Context, string, func(context.Context) (any, error)) (any, error)) *MockLockManagerWithLockCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
