// Code generated by MockGen. DO NOT EDIT.
// Source: planning-poker/internal/infra/boundaries/http (interfaces: API)
//
// Generated by this command:
//
//	mockgen -destination mocks.go -typed -package http . API
//

// Package http is a generated GoMock package.
package http

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// Endpoint mocks base method.
func (m *MockAPI) Endpoint() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Endpoint")
	ret0, _ := ret[0].(string)
	return ret0
}

// Endpoint indicates an expected call of Endpoint.
func (mr *MockAPIMockRecorder) Endpoint() *MockAPIEndpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Endpoint", reflect.TypeOf((*MockAPI)(nil).Endpoint))
	return &MockAPIEndpointCall{Call: call}
}

// MockAPIEndpointCall wrap *gomock.Call
type MockAPIEndpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIEndpointCall) Return(arg0 string) *MockAPIEndpointCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIEndpointCall) Do(f func() string) *MockAPIEndpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIEndpointCall) DoAndReturn(f func() string) *MockAPIEndpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Handle mocks base method.
func (m *MockAPI) Handle() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockAPIMockRecorder) Handle() *MockAPIHandleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockAPI)(nil).Handle))
	return &MockAPIHandleCall{Call: call}
}

// MockAPIHandleCall wrap *gomock.Call
type MockAPIHandleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIHandleCall) Return(arg0 http.Handler) *MockAPIHandleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIHandleCall) Do(f func() http.Handler) *MockAPIHandleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIHandleCall) DoAndReturn(f func() http.Handler) *MockAPIHandleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Methods mocks base method.
func (m *MockAPI) Methods() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Methods")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Methods indicates an expected call of Methods.
func (mr *MockAPIMockRecorder) Methods() *MockAPIMethodsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Methods", reflect.TypeOf((*MockAPI)(nil).Methods))
	return &MockAPIMethodsCall{Call: call}
}

// MockAPIMethodsCall wrap *gomock.Call
type MockAPIMethodsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIMethodsCall) Return(arg0 []string) *MockAPIMethodsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIMethodsCall) Do(f func() []string) *MockAPIMethodsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIMethodsCall) DoAndReturn(f func() []string) *MockAPIMethodsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
