app:
  name: go-study
  version: "0.0.1"
  monitoring:
    trace-url: http://localhost:9411/api/v2/spans
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database-name: hello
kafka:
  host: localhost:9092
  consumers:
    go-study:
      host: localhost:9092
      topic: go-study.hello
      group-id: my-group-1
      qnt-consumers: 10
      trace-enabled: false
workers:
  hello-producer:
    topic: go-study.hello
    interval-millis: 1000
