server:
  port: 8082
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/auth/realms/test/protocol/openid-connect/certs
          issuer-uri: http://localhost:8081/auth/realms/test