// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks.go -package outbox
//

// Package outbox is a generated GoMock package.
package outbox

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// FetchPendingBatch mocks base method.
func (m *MockOutboxRepository) FetchPendingBatch(ctx context.Context, limit int) ([]*OutboxMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPendingBatch", ctx, limit)
	ret0, _ := ret[0].([]*OutboxMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPendingBatch indicates an expected call of FetchPendingBatch.
func (mr *MockOutboxRepositoryMockRecorder) FetchPendingBatch(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPendingBatch", reflect.TypeOf((*MockOutboxRepository)(nil).FetchPendingBatch), ctx, limit)
}

// Insert mocks base method.
func (m *MockOutboxRepository) Insert(ctx context.Context, msg *OutboxMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockOutboxRepositoryMockRecorder) Insert(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockOutboxRepository)(nil).Insert), ctx, msg)
}

// MarkFailed mocks base method.
func (m *MockOutboxRepository) MarkFailed(ctx context.Context, msgID, lastError string, maxAttempts int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, msgID, lastError, maxAttempts)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockOutboxRepositoryMockRecorder) MarkFailed(ctx, msgID, lastError, maxAttempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkFailed), ctx, msgID, lastError, maxAttempts)
}

// MarkSent mocks base method.
func (m *MockOutboxRepository) MarkSent(ctx context.Context, msgID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSent", ctx, msgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSent indicates an expected call of MarkSent.
func (mr *MockOutboxRepositoryMockRecorder) MarkSent(ctx, msgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSent", reflect.TypeOf((*MockOutboxRepository)(nil).MarkSent), ctx, msgID)
}
