apiVersion: v1
kind: Service
metadata:
  name: k8s-test-app-service
  namespace: k8s-test-app
spec:
  selector:
    app: k8s-test-app
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 3333
    protocol: TCP
    nodePort: 32401
