_format_version: "3.0"
_transform: true

services:
- host: $K8S_CLUSTER_IP
  name: k8s-test-app
  port: 32401
  protocol: http
  routes:
  - name: k8s-test-app
    paths:
    - /k8s-test-app
    strip_path: true
