apiVersion: 1
datasources:
  - name: Zipkin
    uid: zipkin
    type: zipkin
    orgId: 1
    access: proxy
    url: http://zipkin:9411
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
