services:
  gitea:
    image: docker.gitea.com/gitea:1.23.8-rootless
    container_name: gitea
    hostname: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - ./gitea/data:/var/lib/gitea
      - ./gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 3000
      - 2222
    ports:
      - "3000:3000"
      - "2222:2222"
    networks:
      - self_hosted
    depends_on:
      - db

  gitea-runner:
    image: gitea/act_runner:0.2.11
    container_name: gitea-runner
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=${GITEA_INSTANCE_URL}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_REGISTRATION_TOKEN}
      - GITEA_RUNNER_NAME=gitea-runner-default
    volumes:
      - ./gitea-runner/config.yaml:/config.yaml
      - ./gitea-runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4001:4001"
    networks:
      - self_hosted

  db:
    image: postgres:14
    container_name: gitea_db
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - self_hosted

  # cloudflared-gitea:
  #   image: cloudflare/cloudflared
  #   container_name: gitea_cloudflared
  #   restart: unless-stopped
  #   command: tunnel --no-autoupdate run --url http://gitea:3000
  #   environment:
  #     - TUNNEL_TOKEN=${CLOUDFLARE_GITEA_TOKEN}
  #   depends_on:
  #     - gitea
  #   networks:
  #     - gitea_network

networks:
  self_hosted:
    external: true
    name: self_hosted
