// Code generated by MockGen. DO NOT EDIT.
// Source: planning-poker/internal/application/planningpoker/usecase (interfaces: CreateRoomUseCase)
//
// Generated by this command:
//
//	mockgen -destination mocks.go -typed -package usecase . CreateRoomUseCase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateRoomUseCase is a mock of CreateRoomUseCase interface.
type MockCreateRoomUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateRoomUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateRoomUseCaseMockRecorder is the mock recorder for MockCreateRoomUseCase.
type MockCreateRoomUseCaseMockRecorder struct {
	mock *MockCreateRoomUseCase
}

// NewMockCreateRoomUseCase creates a new mock instance.
func NewMockCreateRoomUseCase(ctrl *gomock.Controller) *MockCreateRoomUseCase {
	mock := &MockCreateRoomUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateRoomUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateRoomUseCase) EXPECT() *MockCreateRoomUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateRoomUseCase) Execute(ctx context.Context, cmd CreateRoomCommand) (CreateRoomOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, cmd)
	ret0, _ := ret[0].(CreateRoomOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateRoomUseCaseMockRecorder) Execute(ctx, cmd any) *MockCreateRoomUseCaseExecuteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateRoomUseCase)(nil).Execute), ctx, cmd)
	return &MockCreateRoomUseCaseExecuteCall{Call: call}
}

// MockCreateRoomUseCaseExecuteCall wrap *gomock.Call
type MockCreateRoomUseCaseExecuteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCreateRoomUseCaseExecuteCall) Return(arg0 CreateRoomOutput, arg1 error) *MockCreateRoomUseCaseExecuteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCreateRoomUseCaseExecuteCall) Do(f func(context.Context, CreateRoomCommand) (CreateRoomOutput, error)) *MockCreateRoomUseCaseExecuteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCreateRoomUseCaseExecuteCall) DoAndReturn(f func(context.Context, CreateRoomCommand) (CreateRoomOutput, error)) *MockCreateRoomUseCaseExecuteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
