apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-java
  namespace: k8s-test-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-test-java
  template:
    metadata:
      labels:
        app: k8s-test-java
    spec:
      containers:
      - name: k8s-test-java
        image: bruno303/k8s-test-java:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
