apiVersion: v1
kind: Service
metadata:
  name: k8s-test-java
  namespace: k8s-test-java
spec:
  selector:
    app: k8s-test-java
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 32402
