// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bruno303/go-toolkit/pkg/metric (interfaces: Meter)
//
// Generated by this command:
//
//	mockgen -destination mocks.go -typed -package metric github.com/bruno303/go-toolkit/pkg/metric Meter
//

// Package metric is a generated GoMock package.
package metric

import (
	context "context"
	reflect "reflect"

	metric "github.com/bruno303/go-toolkit/pkg/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockMeter is a mock of Meter interface.
type MockMeter struct {
	ctrl     *gomock.Controller
	recorder *MockMeterMockRecorder
	isgomock struct{}
}

// MockMeterMockRecorder is the mock recorder for MockMeter.
type MockMeterMockRecorder struct {
	mock *MockMeter
}

// NewMockMeter creates a new mock instance.
func NewMockMeter(ctrl *gomock.Controller) *MockMeter {
	mock := &MockMeter{ctrl: ctrl}
	mock.recorder = &MockMeterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeter) EXPECT() *MockMeterMockRecorder {
	return m.recorder
}

// AddCounter mocks base method.
func (m *MockMeter) AddCounter(ctx context.Context, name, description, unit string, value float64, attrs ...metric.Attribute) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, description, unit, value}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddCounter", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCounter indicates an expected call of AddCounter.
func (mr *MockMeterMockRecorder) AddCounter(ctx, name, description, unit, value any, attrs ...any) *MockMeterAddCounterCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, description, unit, value}, attrs...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCounter", reflect.TypeOf((*MockMeter)(nil).AddCounter), varargs...)
	return &MockMeterAddCounterCall{Call: call}
}

// MockMeterAddCounterCall wrap *gomock.Call
type MockMeterAddCounterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMeterAddCounterCall) Return(arg0 error) *MockMeterAddCounterCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMeterAddCounterCall) Do(f func(context.Context, string, string, string, float64, ...metric.Attribute) error) *MockMeterAddCounterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMeterAddCounterCall) DoAndReturn(f func(context.Context, string, string, string, float64, ...metric.Attribute) error) *MockMeterAddCounterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddGauge mocks base method.
func (m *MockMeter) AddGauge(ctx context.Context, name, description, unit string, value float64, attrs ...metric.Attribute) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, description, unit, value}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddGauge", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGauge indicates an expected call of AddGauge.
func (mr *MockMeterMockRecorder) AddGauge(ctx, name, description, unit, value any, attrs ...any) *MockMeterAddGaugeCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, description, unit, value}, attrs...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGauge", reflect.TypeOf((*MockMeter)(nil).AddGauge), varargs...)
	return &MockMeterAddGaugeCall{Call: call}
}

// MockMeterAddGaugeCall wrap *gomock.Call
type MockMeterAddGaugeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMeterAddGaugeCall) Return(arg0 error) *MockMeterAddGaugeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMeterAddGaugeCall) Do(f func(context.Context, string, string, string, float64, ...metric.Attribute) error) *MockMeterAddGaugeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMeterAddGaugeCall) DoAndReturn(f func(context.Context, string, string, string, float64, ...metric.Attribute) error) *MockMeterAddGaugeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
