root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/api cmd/api/*.go"
bin = "tmp/api"
exclude_dir = ["tmp", "vendor"]
exclude_regex = ["_test\\.go"]
follow_symlink = true
log = "air.log"
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = 5000

[log]
time = true
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
