services:
  pdfding:
    container_name: pdfding
    hostname: pdfding
    image: mrmn/pdfding:latest
    restart: unless-stopped
    volumes:
      - ${VOLUMES_DIR}/sqlite_data:/home/nonroot/pdfding/db
      - ${VOLUMES_DIR}/media:/home/nonroot/pdfding/media
    environment:
      - DEFAULT_THEME=${DEFAULT_THEME:-dark}
      - DEFAULT_THEME_COLOR=${DEFAULT_THEME_COLOR:-blue}
      # use a long random secret
      - SECRET_KEY=${SECRET_KEY:-some_secret}
      # the domain where you want to access PdfDing, e.g. pdfding.com
      - HOST_NAME=${HOST_NAME:-127.0.0.1}
      # In production set the following values to True
      - CSRF_COOKIE_SECURE=${CSRF_COOKIE_SECURE:-FALSE}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-FALSE}
      - DISABLE_USER_SIGNUP=TRUE
    expose:
      - 8000
    networks:
      - self_hosted

networks:
  self_hosted:
    external: true
    name: self_hosted
