apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: planning-poker-backend
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-stg
    kind: ClusterSecretStore
  target:
    name: planning-poker-backend
  data:
    - secretKey: ADMIN_API_KEY
      remoteRef:
        key: PLANNING_POKER_ADMIN_API_KEY