apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-prd
    kind: ClusterSecretStore
  target:
    name: gitea
  data:
    - secretKey: GITEA_RUNNER_REGISTRATION_TOKEN
      remoteRef:
        key: GITEA_RUNNER_REGISTRATION_TOKEN