// Code generated by MockGen. DO NOT EDIT.
// Source: planning-poker/internal/domain (interfaces: Hub,AdminHub,Bus)
//
// Generated by this command:
//
//	mockgen -destination mocks.go -typed -package domain . Hub,AdminHub,Bus
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	entity "planning-poker/internal/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHub is a mock of Hub interface.
type MockHub struct {
	ctrl     *gomock.Controller
	recorder *MockHubMockRecorder
	isgomock struct{}
}

// MockHubMockRecorder is the mock recorder for MockHub.
type MockHubMockRecorder struct {
	mock *MockHub
}

// NewMockHub creates a new mock instance.
func NewMockHub(ctrl *gomock.Controller) *MockHub {
	mock := &MockHub{ctrl: ctrl}
	mock.recorder = &MockHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHub) EXPECT() *MockHubMockRecorder {
	return m.recorder
}

// AddBus mocks base method.
func (m *MockHub) AddBus(ctx context.Context, clientID string, bus Bus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddBus", ctx, clientID, bus)
}

// AddBus indicates an expected call of AddBus.
func (mr *MockHubMockRecorder) AddBus(ctx, clientID, bus any) *MockHubAddBusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBus", reflect.TypeOf((*MockHub)(nil).AddBus), ctx, clientID, bus)
	return &MockHubAddBusCall{Call: call}
}

// MockHubAddBusCall wrap *gomock.Call
type MockHubAddBusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHubAddBusCall) Return() *MockHubAddBusCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHubAddBusCall) Do(f func(context.Context, string, Bus)) *MockHubAddBusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHubAddBusCall) DoAndReturn(f func(context.Context, string, Bus)) *MockHubAddBusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddClient mocks base method.
func (m *MockHub) AddClient(c *entity.Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddClient", c)
}

// AddClient indicates an expected call of AddClient.
func (mr *MockHubMockRecorder) AddClient(c any) *MockHubAddClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClient", reflect.TypeOf((*MockHub)(nil).AddClient), c)
	return &MockHubAddClientCall{Call: call}
}

// MockHubAddClientCall wrap *gomock.Call
type MockHubAddClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MockHubAddClientCall) Return() *MockHubAddClientCall {
	c_2.Call = c_2.Call.Return()
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MockHubAddClientCall) Do(f func(*entity.Client)) *MockHubAddClientCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MockHubAddClientCall) DoAndReturn(f func(*entity.Client)) *MockHubAddClientCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// BroadcastToRoom mocks base method.
func (m *MockHub) BroadcastToRoom(ctx context.Context, roomID string, message any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastToRoom", ctx, roomID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastToRoom indicates an expected call of BroadcastToRoom.
func (mr *MockHubMockRecorder) BroadcastToRoom(ctx, roomID, message any) *MockHubBroadcastToRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastToRoom", reflect.TypeOf((*MockHub)(nil).BroadcastToRoom), ctx, roomID, message)
	return &MockHubBroadcastToRoomCall{Call: call}
}

// MockHubBroadcastToRoomCall wrap *gomock.Call
type MockHubBroadcastToRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHubBroadcastToRoomCall) Return(arg0 error) *MockHubBroadcastToRoomCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHubBroadcastToRoomCall) Do(f func(context.Context, string, any) error) *MockHubBroadcastToRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHubBroadcastToRoomCall) DoAndReturn(f func(context.Context, string, any) error) *MockHubBroadcastToRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindClientByID mocks base method.
func (m *MockHub) FindClientByID(clientID string) (*entity.Client, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindClientByID", clientID)
	ret0, _ := ret[0].(*entity.Client)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// FindClientByID indicates an expected call of FindClientByID.
func (mr *MockHubMockRecorder) FindClientByID(clientID any) *MockHubFindClientByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindClientByID", reflect.TypeOf((*MockHub)(nil).FindClientByID), clientID)
	return &MockHubFindClientByIDCall{Call: call}
}

// MockHubFindClientByIDCall wrap *gomock.Call
type MockHubFindClientByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHubFindClientByIDCall) Return(arg0 *entity.Client, arg1 bool) *MockHubFindClientByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHubFindClientByIDCall) Do(f func(string) (*entity.Client, bool)) *MockHubFindClientByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHubFindClientByIDCall) DoAndReturn(f func(string) (*entity.Client, bool)) *MockHubFindClientByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetBus mocks base method.
func (m *MockHub) GetBus(clientID string) (Bus, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBus", clientID)
	ret0, _ := ret[0].(Bus)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetBus indicates an expected call of GetBus.
func (mr *MockHubMockRecorder) GetBus(clientID any) *MockHubGetBusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBus", reflect.TypeOf((*MockHub)(nil).GetBus), clientID)
	return &MockHubGetBusCall{Call: call}
}

// MockHubGetBusCall wrap *gomock.Call
type MockHubGetBusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHubGetBusCall) Return(arg0 Bus, arg1 bool) *MockHubGetBusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHubGetBusCall) Do(f func(string) (Bus, bool)) *MockHubGetBusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHubGetBusCall) DoAndReturn(f func(string) (Bus, bool)) *MockHubGetBusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRoom mocks base method.
func (m *MockHub) GetRoom(ctx context.Context, roomID string) (*entity.Room, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, roomID)
	ret0, _ := ret[0].(*entity.Room)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockHubMockRecorder) GetRoom(ctx, roomID any) *MockHubGetRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockHub)(nil).GetRoom), ctx, roomID)
	return &MockHubGetRoomCall{Call: call}
}

// MockHubGetRoomCall wrap *gomock.Call
type MockHubGetRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHubGetRoomCall) Return(arg0 *entity.Room, arg1 bool) *MockHubGetRoomCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHubGetRoomCall) Do(f func(context.Context, string) (*entity.Room, bool)) *MockHubGetRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHubGetRoomCall) DoAndReturn(f func(context.Context, string) (*entity.Room, bool)) *MockHubGetRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewRoom mocks base method.
func (m *MockHub) NewRoom(ctx context.Context, owner string) *entity.Room {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRoom", ctx, owner)
	ret0, _ := ret[0].(*entity.Room)
	return ret0
}

// NewRoom indicates an expected call of NewRoom.
func (mr *MockHubMockRecorder) NewRoom(ctx, owner any) *MockHubNewRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRoom", reflect.TypeOf((*MockHub)(nil).NewRoom), ctx, owner)
	return &MockHubNewRoomCall{Call: call}
}

// MockHubNewRoomCall wrap *gomock.Call
type MockHubNewRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHubNewRoomCall) Return(arg0 *entity.Room) *MockHubNewRoomCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHubNewRoomCall) Do(f func(context.Context, string) *entity.Room) *MockHubNewRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHubNewRoomCall) DoAndReturn(f func(context.Context, string) *entity.Room) *MockHubNewRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveBus mocks base method.
func (m *MockHub) RemoveBus(ctx context.Context, clientID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveBus", ctx, clientID)
}

// RemoveBus indicates an expected call of RemoveBus.
func (mr *MockHubMockRecorder) RemoveBus(ctx, clientID any) *MockHubRemoveBusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBus", reflect.TypeOf((*MockHub)(nil).RemoveBus), ctx, clientID)
	return &MockHubRemoveBusCall{Call: call}
}

// MockHubRemoveBusCall wrap *gomock.Call
type MockHubRemoveBusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHubRemoveBusCall) Return() *MockHubRemoveBusCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHubRemoveBusCall) Do(f func(context.Context, string)) *MockHubRemoveBusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHubRemoveBusCall) DoAndReturn(f func(context.Context, string)) *MockHubRemoveBusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveClient mocks base method.
func (m *MockHub) RemoveClient(ctx context.Context, clientID, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveClient", ctx, clientID, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveClient indicates an expected call of RemoveClient.
func (mr *MockHubMockRecorder) RemoveClient(ctx, clientID, roomID any) *MockHubRemoveClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveClient", reflect.TypeOf((*MockHub)(nil).RemoveClient), ctx, clientID, roomID)
	return &MockHubRemoveClientCall{Call: call}
}

// MockHubRemoveClientCall wrap *gomock.Call
type MockHubRemoveClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHubRemoveClientCall) Return(arg0 error) *MockHubRemoveClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHubRemoveClientCall) Do(f func(context.Context, string, string) error) *MockHubRemoveClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHubRemoveClientCall) DoAndReturn(f func(context.Context, string, string) error) *MockHubRemoveClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveRoom mocks base method.
func (m *MockHub) RemoveRoom(roomID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveRoom", roomID)
}

// RemoveRoom indicates an expected call of RemoveRoom.
func (mr *MockHubMockRecorder) RemoveRoom(roomID any) *MockHubRemoveRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRoom", reflect.TypeOf((*MockHub)(nil).RemoveRoom), roomID)
	return &MockHubRemoveRoomCall{Call: call}
}

// MockHubRemoveRoomCall wrap *gomock.Call
type MockHubRemoveRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHubRemoveRoomCall) Return() *MockHubRemoveRoomCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHubRemoveRoomCall) Do(f func(string)) *MockHubRemoveRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHubRemoveRoomCall) DoAndReturn(f func(string)) *MockHubRemoveRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveRoom mocks base method.
func (m *MockHub) SaveRoom(ctx context.Context, room *entity.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRoom", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRoom indicates an expected call of SaveRoom.
func (mr *MockHubMockRecorder) SaveRoom(ctx, room any) *MockHubSaveRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRoom", reflect.TypeOf((*MockHub)(nil).SaveRoom), ctx, room)
	return &MockHubSaveRoomCall{Call: call}
}

// MockHubSaveRoomCall wrap *gomock.Call
type MockHubSaveRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHubSaveRoomCall) Return(arg0 error) *MockHubSaveRoomCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHubSaveRoomCall) Do(f func(context.Context, *entity.Room) error) *MockHubSaveRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHubSaveRoomCall) DoAndReturn(f func(context.Context, *entity.Room) error) *MockHubSaveRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAdminHub is a mock of AdminHub interface.
type MockAdminHub struct {
	ctrl     *gomock.Controller
	recorder *MockAdminHubMockRecorder
	isgomock struct{}
}

// MockAdminHubMockRecorder is the mock recorder for MockAdminHub.
type MockAdminHubMockRecorder struct {
	mock *MockAdminHub
}

// NewMockAdminHub creates a new mock instance.
func NewMockAdminHub(ctrl *gomock.Controller) *MockAdminHub {
	mock := &MockAdminHub{ctrl: ctrl}
	mock.recorder = &MockAdminHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminHub) EXPECT() *MockAdminHubMockRecorder {
	return m.recorder
}

// GetRooms mocks base method.
func (m *MockAdminHub) GetRooms() []*entity.Room {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRooms")
	ret0, _ := ret[0].([]*entity.Room)
	return ret0
}

// GetRooms indicates an expected call of GetRooms.
func (mr *MockAdminHubMockRecorder) GetRooms() *MockAdminHubGetRoomsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRooms", reflect.TypeOf((*MockAdminHub)(nil).GetRooms))
	return &MockAdminHubGetRoomsCall{Call: call}
}

// MockAdminHubGetRoomsCall wrap *gomock.Call
type MockAdminHubGetRoomsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminHubGetRoomsCall) Return(arg0 []*entity.Room) *MockAdminHubGetRoomsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminHubGetRoomsCall) Do(f func() []*entity.Room) *MockAdminHubGetRoomsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminHubGetRoomsCall) DoAndReturn(f func() []*entity.Room) *MockAdminHubGetRoomsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBus is a mock of Bus interface.
type MockBus struct {
	ctrl     *gomock.Controller
	recorder *MockBusMockRecorder
	isgomock struct{}
}

// MockBusMockRecorder is the mock recorder for MockBus.
type MockBusMockRecorder struct {
	mock *MockBus
}

// NewMockBus creates a new mock instance.
func NewMockBus(ctrl *gomock.Controller) *MockBus {
	mock := &MockBus{ctrl: ctrl}
	mock.recorder = &MockBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBus) EXPECT() *MockBusMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBus) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBusMockRecorder) Close() *MockBusCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBus)(nil).Close))
	return &MockBusCloseCall{Call: call}
}

// MockBusCloseCall wrap *gomock.Call
type MockBusCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBusCloseCall) Return(arg0 error) *MockBusCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBusCloseCall) Do(f func() error) *MockBusCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBusCloseCall) DoAndReturn(f func() error) *MockBusCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Listen mocks base method.
func (m *MockBus) Listen(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Listen", ctx)
}

// Listen indicates an expected call of Listen.
func (mr *MockBusMockRecorder) Listen(ctx any) *MockBusListenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockBus)(nil).Listen), ctx)
	return &MockBusListenCall{Call: call}
}

// MockBusListenCall wrap *gomock.Call
type MockBusListenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBusListenCall) Return() *MockBusListenCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBusListenCall) Do(f func(context.Context)) *MockBusListenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBusListenCall) DoAndReturn(f func(context.Context)) *MockBusListenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RoomID mocks base method.
func (m *MockBus) RoomID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomID")
	ret0, _ := ret[0].(string)
	return ret0
}

// RoomID indicates an expected call of RoomID.
func (mr *MockBusMockRecorder) RoomID() *MockBusRoomIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomID", reflect.TypeOf((*MockBus)(nil).RoomID))
	return &MockBusRoomIDCall{Call: call}
}

// MockBusRoomIDCall wrap *gomock.Call
type MockBusRoomIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBusRoomIDCall) Return(arg0 string) *MockBusRoomIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBusRoomIDCall) Do(f func() string) *MockBusRoomIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBusRoomIDCall) DoAndReturn(f func() string) *MockBusRoomIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Send mocks base method.
func (m *MockBus) Send(ctx context.Context, message any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockBusMockRecorder) Send(ctx, message any) *MockBusSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBus)(nil).Send), ctx, message)
	return &MockBusSendCall{Call: call}
}

// MockBusSendCall wrap *gomock.Call
type MockBusSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBusSendCall) Return(arg0 error) *MockBusSendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBusSendCall) Do(f func(context.Context, any) error) *MockBusSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBusSendCall) DoAndReturn(f func(context.Context, any) error) *MockBusSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
