apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler-stg
spec:
  provider:
    doppler:
      project: homelab
      config: stg
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-stg
            namespace: eso
            key: token