apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-prd
spec:
  provider:
    doppler:
      project: homelab
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            namespace: eso
            key: token