// Code generated by MockGen. DO NOT EDIT.
// Source: transaction-manager.go
//
// Generated by this command:
//
//	mockgen -source=transaction-manager.go -destination=mocks.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	transaction "github.com/bruno303/study-topics/go-study/internal/application/transaction"
	gomock "go.uber.org/mock/gomock"
)

// MockUnitOfWorkFactory is a mock of UnitOfWorkFactory interface.
type MockUnitOfWorkFactory struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkFactoryMockRecorder
	isgomock struct{}
}

// MockUnitOfWorkFactoryMockRecorder is the mock recorder for MockUnitOfWorkFactory.
type MockUnitOfWorkFactoryMockRecorder struct {
	mock *MockUnitOfWorkFactory
}

// NewMockUnitOfWorkFactory creates a new mock instance.
func NewMockUnitOfWorkFactory(ctrl *gomock.Controller) *MockUnitOfWorkFactory {
	mock := &MockUnitOfWorkFactory{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOfWorkFactory) EXPECT() *MockUnitOfWorkFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUnitOfWorkFactory) Create() transaction.UnitOfWork {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(transaction.UnitOfWork)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUnitOfWorkFactoryMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUnitOfWorkFactory)(nil).Create))
}
