// Code generated by MockGen. DO NOT EDIT.
// Source: pgx-unit-of-work.go
//
// Generated by this command:
//
//	mockgen -source=pgx-unit-of-work.go -destination=mocks.go -package repository
//

// Package repository is a generated GoMock package.
package repository
