// Code generated by MockGen. DO NOT EDIT.
// Source: planning-poker/internal/infra/boundaries/bus/redis (interfaces: RedisClient)
//
// Generated by this command:
//
//	mockgen -destination mocks.go -typed -package redis . RedisClient
//

// Package redis is a generated GoMock package.
package redis

import (
	context "context"
	reflect "reflect"
	time "time"

	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
)

// MockRedisClient is a mock of RedisClient interface.
type MockRedisClient struct {
	ctrl     *gomock.Controller
	recorder *MockRedisClientMockRecorder
	isgomock struct{}
}

// MockRedisClientMockRecorder is the mock recorder for MockRedisClient.
type MockRedisClientMockRecorder struct {
	mock *MockRedisClient
}

// NewMockRedisClient creates a new mock instance.
func NewMockRedisClient(ctrl *gomock.Controller) *MockRedisClient {
	mock := &MockRedisClient{ctrl: ctrl}
	mock.recorder = &MockRedisClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisClient) EXPECT() *MockRedisClientMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockRedisClient) Del(ctx context.Context, keys ...string) *redis.IntCmd {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	ret0, _ := ret[0].(*redis.IntCmd)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockRedisClientMockRecorder) Del(ctx any, keys ...any) *MockRedisClientDelCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, keys...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockRedisClient)(nil).Del), varargs...)
	return &MockRedisClientDelCall{Call: call}
}

// MockRedisClientDelCall wrap *gomock.Call
type MockRedisClientDelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientDelCall) Return(arg0 *redis.IntCmd) *MockRedisClientDelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientDelCall) Do(f func(context.Context, ...string) *redis.IntCmd) *MockRedisClientDelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientDelCall) DoAndReturn(f func(context.Context, ...string) *redis.IntCmd) *MockRedisClientDelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockRedisClient) Get(ctx context.Context, key string) *redis.StringCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*redis.StringCmd)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRedisClientMockRecorder) Get(ctx, key any) *MockRedisClientGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedisClient)(nil).Get), ctx, key)
	return &MockRedisClientGetCall{Call: call}
}

// MockRedisClientGetCall wrap *gomock.Call
type MockRedisClientGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientGetCall) Return(arg0 *redis.StringCmd) *MockRedisClientGetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientGetCall) Do(f func(context.Context, string) *redis.StringCmd) *MockRedisClientGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientGetCall) DoAndReturn(f func(context.Context, string) *redis.StringCmd) *MockRedisClientGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Publish mocks base method.
func (m *MockRedisClient) Publish(ctx context.Context, channel string, message any) *redis.IntCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, channel, message)
	ret0, _ := ret[0].(*redis.IntCmd)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockRedisClientMockRecorder) Publish(ctx, channel, message any) *MockRedisClientPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockRedisClient)(nil).Publish), ctx, channel, message)
	return &MockRedisClientPublishCall{Call: call}
}

// MockRedisClientPublishCall wrap *gomock.Call
type MockRedisClientPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientPublishCall) Return(arg0 *redis.IntCmd) *MockRedisClientPublishCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientPublishCall) Do(f func(context.Context, string, any) *redis.IntCmd) *MockRedisClientPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientPublishCall) DoAndReturn(f func(context.Context, string, any) *redis.IntCmd) *MockRedisClientPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Scan mocks base method.
func (m *MockRedisClient) Scan(ctx context.Context, count uint64, match string, cursor int64) *redis.ScanCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", ctx, count, match, cursor)
	ret0, _ := ret[0].(*redis.ScanCmd)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockRedisClientMockRecorder) Scan(ctx, count, match, cursor any) *MockRedisClientScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockRedisClient)(nil).Scan), ctx, count, match, cursor)
	return &MockRedisClientScanCall{Call: call}
}

// MockRedisClientScanCall wrap *gomock.Call
type MockRedisClientScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientScanCall) Return(arg0 *redis.ScanCmd) *MockRedisClientScanCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientScanCall) Do(f func(context.Context, uint64, string, int64) *redis.ScanCmd) *MockRedisClientScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientScanCall) DoAndReturn(f func(context.Context, uint64, string, int64) *redis.ScanCmd) *MockRedisClientScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Set mocks base method.
func (m *MockRedisClient) Set(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, expiration)
	ret0, _ := ret[0].(*redis.StatusCmd)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRedisClientMockRecorder) Set(ctx, key, value, expiration any) *MockRedisClientSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRedisClient)(nil).Set), ctx, key, value, expiration)
	return &MockRedisClientSetCall{Call: call}
}

// MockRedisClientSetCall wrap *gomock.Call
type MockRedisClientSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientSetCall) Return(arg0 *redis.StatusCmd) *MockRedisClientSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientSetCall) Do(f func(context.Context, string, any, time.Duration) *redis.StatusCmd) *MockRedisClientSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientSetCall) DoAndReturn(f func(context.Context, string, any, time.Duration) *redis.StatusCmd) *MockRedisClientSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Subscribe mocks base method.
func (m *MockRedisClient) Subscribe(ctx context.Context, channels ...string) *redis.PubSub {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range channels {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Subscribe", varargs...)
	ret0, _ := ret[0].(*redis.PubSub)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockRedisClientMockRecorder) Subscribe(ctx any, channels ...any) *MockRedisClientSubscribeCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, channels...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockRedisClient)(nil).Subscribe), varargs...)
	return &MockRedisClientSubscribeCall{Call: call}
}

// MockRedisClientSubscribeCall wrap *gomock.Call
type MockRedisClientSubscribeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisClientSubscribeCall) Return(arg0 *redis.PubSub) *MockRedisClientSubscribeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisClientSubscribeCall) Do(f func(context.Context, ...string) *redis.PubSub) *MockRedisClientSubscribeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisClientSubscribeCall) DoAndReturn(f func(context.Context, ...string) *redis.PubSub) *MockRedisClientSubscribeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
