version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    networks:
      - oauth-test
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

networks:
  oauth-test: