{{- if .Values.backend.secrets.adminApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "planning-poker.fullname" . }}-backend
  labels:
    {{- include "planning-poker.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  ADMIN_API_KEY: {{ .Values.backend.secrets.adminApiKey | b64enc | quote }}
{{- end }}
