apiVersion: v1
kind: Service
metadata:
  name: {{ include "planning-poker.fullname" . }}-backend
  labels:
    {{- include "planning-poker.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      name: http-metrics
    {{- end }}
  selector:
    {{- include "planning-poker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
