{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "planning-poker.fullname" . }}-redis
  labels:
    {{- include "planning-poker.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      {{- include "planning-poker.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "planning-poker.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.port }}
              name: redis
          {{- if or .Values.redis.probes.liveness.enabled .Values.redis.probes.readiness.enabled }}
          {{- if .Values.redis.probes.liveness.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.redis.probes.liveness.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.redis.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.redis.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.redis.probes.readiness.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.redis.probes.readiness.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.redis.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.redis.probes.readiness.failureThreshold }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- with .Values.redis.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.redis.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.redis.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
