apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-prd
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-secret
  data:
    - secretKey: token
      remoteRef:
        key: CLOUDFLARE_TUNNEL_TOKEN