apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pdfding-secret
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-prd
    kind: ClusterSecretStore
  target:
    name: pdfding-secret
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: PDFDING_SECRET_KEY