CREATE TABLE HELLO_DATA (
    ID VARCHAR(100) PRIMARY KEY,
    NAME VARCHAR(300) NOT NULL,
    AGE INT
);

CREATE TABLE OUTBOX_MESSAGES (
    ID UUID PRIMARY KEY,
    TOPIC VARCHAR(255) NOT NULL,
    PAYLOAD JSONB NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    ATTEMPT_COUNT INT NOT NULL DEFAULT 0,
    AVAILABLE_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    LAST_ERROR TEXT,
    PUBLISHED_AT TIMESTAMPTZ,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IDX_OUTBOX_MESSAGES_STATUS_AVAILABLE_AT
    ON OUTBOX_MESSAGES (STATUS, AVAILABLE_AT, CREATED_AT);
