CREATE TABLE HELLO_DATA (
    ID VARCHAR(100) PRIMARY KEY,
    NAME VARCHAR(300) NOT NULL,
    AGE INT
);

CREATE TABLE OUTBOX (
    ID VARCHAR(100) PRIMARY KEY,
    TOPIC VARCHAR(255) NOT NULL,
    MESSAGE_KEY VARCHAR(255) NOT NULL,
    PAYLOAD BYTEA NOT NULL,
    HEADERS JSONB,
    STATUS VARCHAR(20) NOT NULL,
    ATTEMPT INT NOT NULL,
    NEXT_ATTEMPT TIMESTAMPTZ NOT NULL,
    PUBLISHED_AT TIMESTAMPTZ,
    LAST_ERROR TEXT,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    UPDATED_AT TIMESTAMPTZ NOT NULL,
    DELETED_AT TIMESTAMPTZ
);
