name: Planning Poker GitOps

on:
  repository_dispatch:
    types: [planning-poker-tag-push]

env:
  BE_VER: ${{ github.event.client_payload.backend_version }}
  FE_VER: ${{ github.event.client_payload.frontend_version }}

jobs:
  staging-backend:
    runs-on: ubuntu-latest
    permissions: { contents: write, pull-requests: write }
    steps:
      - uses: actions/checkout@v5
      - run: yq eval '.spec.template.spec.containers[0].image = "bruno303/planning-poker-backend:${{ env.BE_VER }}"' -i self_hosted/k8s/planning-poker/staging/backend/deployment.yaml
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: bump/staging/backend-${{ env.BE_VER }}
          title: "[staging] Backend ${{ env.BE_VER }}"
          body: "Bump staging backend to `${{ env.BE_VER }}`"
          commit-message: "chore(staging/backend): bump to ${{ env.BE_VER }}"
          delete-branch: true

  staging-frontend:
    runs-on: ubuntu-latest
    permissions: { contents: write, pull-requests: write }
    steps:
      - uses: actions/checkout@v5
      - run: yq eval '.spec.template.spec.containers[0].image = "bruno303/planning-poker-frontend:${{ env.FE_VER }}-stg"' -i self_hosted/k8s/planning-poker/staging/frontend/deployment.yaml
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: bump/staging/frontend-${{ env.FE_VER }}-stg
          title: "[staging] Frontend ${{ env.FE_VER }}"
          body: "Bump staging frontend to `${{ env.FE_VER }}`"
          commit-message: "chore(staging/frontend): bump to ${{ env.FE_VER }}"
          delete-branch: true

  production-backend:
    runs-on: ubuntu-latest
    permissions: { contents: write, pull-requests: write }
    steps:
      - uses: actions/checkout@v5
      - run: yq eval '.spec.template.spec.containers[0].image = "bruno303/planning-poker-backend:${{ env.BE_VER }}"' -i self_hosted/k8s/planning-poker/production/backend/deployment.yaml
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: bump/production/backend-${{ env.BE_VER }}
          title: "[production] Backend ${{ env.BE_VER }}"
          body: "Bump production backend to `${{ env.BE_VER }}`"
          commit-message: "chore(production/backend): bump to ${{ env.BE_VER }}"
          delete-branch: true

  production-frontend:
    runs-on: ubuntu-latest
    permissions: { contents: write, pull-requests: write }
    steps:
      - uses: actions/checkout@v5
      - run: yq eval '.spec.template.spec.containers[0].image = "bruno303/planning-poker-frontend:${{ env.FE_VER }}"' -i self_hosted/k8s/planning-poker/production/frontend/deployment.yaml
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: bump/production/frontend-${{ env.FE_VER }}
          title: "[production] Frontend ${{ env.FE_VER }}"
          body: "Bump production frontend to `${{ env.FE_VER }}`"
          commit-message: "chore(production/frontend): bump to ${{ env.FE_VER }}"
          delete-branch: true
