// Code generated by MockGen. DO NOT EDIT.
// Source: hello-producer.go
//
// Generated by this command:
//
//	mockgen -source=hello-producer.go -destination=mocks.go -package worker
//

// Package worker is a generated GoMock package.
package worker
