// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bruno303/study-topics/go-study/internal/application/repository (interfaces: HelloRepository,OutboxRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks.go -package repository . HelloRepository,OutboxRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	models "github.com/bruno303/study-topics/go-study/internal/application/hello/models"
	gomock "go.uber.org/mock/gomock"
)

// MockHelloRepository is a mock of HelloRepository interface.
type MockHelloRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHelloRepositoryMockRecorder
	isgomock struct{}
}

// MockHelloRepositoryMockRecorder is the mock recorder for MockHelloRepository.
type MockHelloRepositoryMockRecorder struct {
	mock *MockHelloRepository
}

// NewMockHelloRepository creates a new mock instance.
func NewMockHelloRepository(ctrl *gomock.Controller) *MockHelloRepository {
	mock := &MockHelloRepository{ctrl: ctrl}
	mock.recorder = &MockHelloRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelloRepository) EXPECT() *MockHelloRepositoryMockRecorder {
	return m.recorder
}

// ListAll mocks base method.
func (m *MockHelloRepository) ListAll(ctx context.Context) ([]models.HelloData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]models.HelloData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockHelloRepositoryMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockHelloRepository)(nil).ListAll), ctx)
}

// Save mocks base method.
func (m *MockHelloRepository) Save(ctx context.Context, entity *models.HelloData) (*models.HelloData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(*models.HelloData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockHelloRepositoryMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockHelloRepository)(nil).Save), ctx, entity)
}

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// ClaimNext mocks base method.
func (m *MockOutboxRepository) ClaimNext(ctx context.Context, maxAttempts int) (*OutboxMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNext", ctx, maxAttempts)
	ret0, _ := ret[0].(*OutboxMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNext indicates an expected call of ClaimNext.
func (mr *MockOutboxRepositoryMockRecorder) ClaimNext(ctx, maxAttempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNext", reflect.TypeOf((*MockOutboxRepository)(nil).ClaimNext), ctx, maxAttempts)
}

// Enqueue mocks base method.
func (m *MockOutboxRepository) Enqueue(ctx context.Context, msg OutboxMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockOutboxRepositoryMockRecorder) Enqueue(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockOutboxRepository)(nil).Enqueue), ctx, msg)
}

// Update mocks base method.
func (m *MockOutboxRepository) Update(ctx context.Context, msg OutboxMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOutboxRepositoryMockRecorder) Update(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOutboxRepository)(nil).Update), ctx, msg)
}
