// Code generated by MockGen. DO NOT EDIT.
// Source: outbox.go
//
// Generated by this command:
//
//	mockgen -source=outbox.go -destination=outbox_mocks.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/bruno303/study-topics/go-study/internal/application/model"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockOutboxRepository) Enqueue(ctx context.Context, message *model.OutboxMessage) (*model.OutboxMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, message)
	ret0, _ := ret[0].(*model.OutboxMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockOutboxRepositoryMockRecorder) Enqueue(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockOutboxRepository)(nil).Enqueue), ctx, message)
}

// ListPending mocks base method.
func (m *MockOutboxRepository) ListPending(ctx context.Context, limit int, maxAttempts int, now time.Time) ([]model.OutboxMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx, limit, maxAttempts, now)
	ret0, _ := ret[0].([]model.OutboxMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockOutboxRepositoryMockRecorder) ListPending(ctx, limit, maxAttempts, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockOutboxRepository)(nil).ListPending), ctx, limit, maxAttempts, now)
}

// MarkAsError mocks base method.
func (m *MockOutboxRepository) MarkAsError(ctx context.Context, id, lastError string, nextAttempt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsError", ctx, id, lastError, nextAttempt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsError indicates an expected call of MarkAsError.
func (mr *MockOutboxRepositoryMockRecorder) MarkAsError(ctx, id, lastError, nextAttempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsError", reflect.TypeOf((*MockOutboxRepository)(nil).MarkAsError), ctx, id, lastError, nextAttempt)
}

// MarkAsPublished mocks base method.
func (m *MockOutboxRepository) MarkAsPublished(ctx context.Context, id string, publishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPublished", ctx, id, publishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsPublished indicates an expected call of MarkAsPublished.
func (mr *MockOutboxRepositoryMockRecorder) MarkAsPublished(ctx, id, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPublished", reflect.TypeOf((*MockOutboxRepository)(nil).MarkAsPublished), ctx, id, publishedAt)
}
